import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link className="underline ml-4 mr-4 hover:no-underline text-blue-500 hover:text-blue-700 font-bold" href={"/about"}>about</Link>
        <Link className="underline ml-4 mr-4 hover:no-underline text-blue-500 hover:text-blue-700 font-bold" href={"/courses"}>courses</Link>
        {children}
      </body>
    </html>
  );
}
